---
title: "report"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_section: true
    md_extensions: -ascii_identifiers
    css: ./report.css
---

<style type="text/css">
.main-container {
  max-width: 75%;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache.lazy = F)
options(knitr.kable.NA = "−")

library(tidyverse)
source("../functions.R")
```

```{r, cache=T}
df.train.cleaned <- load_train_data("../data/01.input/train") %>%
  clean_data()
```


# データ概要

## 生データ

```{r}
df.train.cleaned %>%
  .[1:5,] %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped"), full_width = F, position = "left")
```

## サマリー

```{r, cache=T}
df.train.cleaned.skimed <- skimr::skim(df.train.cleaned)
```

### character

```{r, cache=T}
df.train.cleaned.skimed %>%
  dplyr::filter(skim_type == "character") %>%
  dplyr::select(
    skim_variable,
    n_missing,
    complete_rate,
    dplyr::starts_with("character")
  ) %>%
  dplyr::rename_with(~ stringr::str_replace(.x, "character.", ""), dplyr::starts_with("character")) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

### logical

```{r, cache=T}
df.train.cleaned.skimed %>%
  dplyr::filter(skim_type == "logical") %>%
  dplyr::select(
    skim_variable,
    n_missing,
    complete_rate,
    dplyr::starts_with("logical")
  ) %>%
  dplyr::rename_with(~ stringr::str_replace(.x, "logical.", ""), dplyr::starts_with("logical")) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

### numeric

```{r, cache=T}
df.train.cleaned.skimed %>%
  dplyr::filter(skim_type == "numeric") %>%
  dplyr::select(
    skim_variable,
    n_missing,
    complete_rate,
    dplyr::starts_with("numeric")
  ) %>%
  dplyr::rename_with(~ stringr::str_replace(.x, "numeric.", ""), dplyr::starts_with("numeric")) %>%
  dplyr::mutate(
    dplyr::across(.cols = c(mean, sd, p0, p25, p50, p75, p100), formattable::comma, digits = 3)
  ) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

### POSIXct

```{r, cache=T}
df.train.cleaned.skimed %>%
  dplyr::filter(skim_type == "POSIXct") %>%
  dplyr::select(
    skim_variable,
    n_missing,
    complete_rate,
    dplyr::starts_with("POSIXct")
  ) %>%
  dplyr::rename_with(~ stringr::str_replace(.x, "POSIXct.", ""), dplyr::starts_with("POSIXct")) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```


# SOC

## 時系列の推移

```{r, fig.align="center", fig.width=8, fig.height=10, cache=T}
df.train.cleaned %>%
  dplyr::mutate(degC_type = factor(Chamber_Temp_degC)) %>%
  ggplot(aes(Time, SOC)) +
    geom_line(aes(colour = degC_type)) +
    labs(
      colour = "Chamber_Temp_degC",
      x = "Time(sec)"
    ) +
    facet_grid(Drive_Cycle ~ .)
```

# 線形モデルの構築

```{r, cache=T, include=F}
model.train <-
  lm(
    data = dplyr::filter(df.train.cleaned, !is.na(prev_Time)),
    formula = diff_SOC ~
      eff_Power +
      eff_Power:(eff_Temp_degC) +
      Current +
      Current:Voltage +
      cumsum_A +
      zero_one_curr_gt_0:Battery_Temp_degC +
      Chamber_Temp_degC
  ) %>% # 0.0250
  step()
```

## モデル

```{r}
broom::tidy(model.train) %>%
  dplyr::mutate(
    dplyr::across(c(estimate, std.error), formattable::comma, digits = 6),
    dplyr::across(statistic,              formattable::comma, digits = 1),
    dplyr::across(p.value,                formattable::comma, digits = 3)
  ) %>%
  knitr::kable(
    format = "html"
  ) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

## スコア

```{r}
# 予測
df.train.with_pred <- df.train.cleaned %>%
  
  # SOC 差分を予測
  dplyr::mutate(
    pred_diff_SOC = predict(model.train, df.train.cleaned) %>% tidyr::replace_na(replace = 0)
  ) %>%
  
  # SOC 差分の累積を算出
  dplyr::group_by(experiment_type) %>%
  dplyr::mutate(eff_SOC = cumsum(pred_diff_SOC)) %>%
  dplyr::ungroup() %>%
  
  dplyr::mutate(
    pred_SOC = 100 + eff_SOC
  )

df.train.with_pred %>%

  dplyr::mutate(diff_SOC = SOC - pred_SOC) %>%
  dplyr::select(
    SOC,
    pred_SOC,
    diff_SOC
  ) %>%
  dplyr::summarise(score = sqrt(mean(diff_SOC^2))) %>%
  dplyr::mutate(score = formattable::comma(score, digits = 5)) %>%
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(full_width = F)
```

## 予測と正解の分布

明らかに 2 群に分かれている。

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
df.train.with_pred %>%
  ggplot(aes(diff_SOC, pred_diff_SOC)) +
    geom_point(size = 0.5, alpha = 1/7) +
    geom_abline(intercept = 0, slope = 1)
```

点を分離する事を考えてみる

```{r}
df.with_flg <- df.train.with_pred %>%
  dplyr::mutate(
    flg = (
      (diff_SOC < -0.0025 | 0.005 < diff_SOC)
      & ((diff_SOC - 0.0025 < pred_diff_SOC) & (pred_diff_SOC < diff_SOC + 0.0025))
    ),
    seg = dplyr::case_when(
      is.na(flg) ~ "NA",
      flg        ~ "TRUE",
      !flg       ~ "FALSE"
    )
  )
```


```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
df.with_flg %>%
  ggplot(aes(diff_SOC, pred_diff_SOC)) +
    geom_point(aes(colour = flg), size = 0.5, alpha = 1/7) +
    geom_abline(intercept = 0, slope = 1)
```


```{r}
df.with_flg %>%

  dplyr::filter((diff_SOC < -0.0025 | 0.005 < diff_SOC)) %>%

  dplyr::group_by(flg) %>%
  dplyr::summarise(
    dplyr::across(
      c(Voltage, diff_V, dV, Current, flg_curr_gt_0, diff_A, dA, Ah, Wh, Power, Battery_Temp_degC, diff_Temp_degC, eff_Power, eff_Temp_degC),
      mean,
      na.rm = T
    ),
    .groups = "drop"
  ) %>%

  dplyr::mutate(
    dplyr::across(c(Voltage, diff_V, dV), formattable::comma, digits = 3),
    dplyr::across(c(Current, diff_A, dA), formattable::comma, digits = 2),
    dplyr::across(c(Ah, Wh, Power, Battery_Temp_degC, diff_Temp_degC, eff_Power, eff_Temp_degC), formattable::comma, digits = 2),
    dplyr::across(flg_curr_gt_0, formattable::percent, digits = 0)
  ) %>%

  knitr::kable(
    format = "html"
  ) %>%
  kableExtra::kable_styling(full_width = F)
```



消耗の激しい箇所に青色が集中しているように見て取れる

```{r, fig.align="center", fig.width=8, fig.height=10, cache=T}
df.with_flg %>%
  ggplot(aes(Time, SOC)) +
    geom_point(aes(colour = seg), size = 0.1) +
    facet_grid(Drive_Cycle ~ .)
```



```{r}
plot_experiment <- function(type, data = df.with_flg) {

  data %>%

    dplyr::filter(
      experiment_type == type
    ) %>%

    dplyr::select(
      Time,
      flg,
      SOC,
      V = Voltage,
      dV,
      A = Current,
      dA
    ) %>%
    tidyr::pivot_longer(cols = -c(Time, flg)) %>%

    dplyr::mutate(
      name = factor(name, levels = c("SOC", "V", "dV", "A", "dA"))
    ) %>%

    ggplot(aes(Time, value)) +
      geom_line(alpha = 1/3) +
      geom_point(aes(colour = flg), size = 0.1) +
      facet_grid(name ~ ., scales = "free_y")
}
```


# Cycle_1

## n_20_Cycle_1

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_20_Cycle_1")
```

## n_10_Cycle_1

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_10_Cycle_1")
```

## z_0_Cycle_1

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("z_0_Cycle_1")
```

## p_10_Cycle_1

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_10_Cycle_1")
```

## p_25_Cycle_1

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_25_Cycle_1")
```

# NN

## n_20_NN

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_20_NN")
```

## n_10_NN

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_10_NN")
```

## z_0_NN

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("z_0_NN")
```

## p_10_NN

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_10_NN")
```

## p_25_NN

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_25_NN")
```

# US06

## n_20_US06

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_20_US06")
```

## n_10_US06

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("n_10_US06")
```

## z_0_US06

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("z_0_US06")
```

## p_10_US06

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_10_US06")
```

## p_25_US06

```{r, fig.align="center", fig.width=7, fig.height=7, cache=T}
plot_experiment("p_25_US06")
```
